var SEQDefault = {		
		'adminData': {
			'GFS': '15',   
			'CSO': 'pi_connectstylev2.swf',
			'OTM': false,
			'OTO': true,
			'AW': 800,
			'AH': 600,
			'TYPE': false,
			'HRO': 'L',
			'RLO': 'T',
			'ICS': false,
			'HGL': '',
			'VGL': '',
			'ET': 'SEQ',
			'SLELD': '120,70',
			'ZHP': '200,200,425,75,3,200,100,425,375',
			'AVP': '233,259',
			'audioList':[],
			'imageList':[]		
		},
		'DCKLD': '120,120',
		'SEQData': [{
					'label_value': '',
					'hint_value': '%n%',
					'holder_x': 0,
					'holder_y': 0,
					'image_data': '',
					'doc_x': 100,
					'doc_y': 100,
					'image_data_1': 'N',
					'feedback_value': '',						
					'zoom_parameter': '',
					'hint_parameter': '',
					'transparent_border': 'T',
					'transparent': 'F',
					'transparent_hint': 'F',
					'transparent_border_1': 'F',
					'transparent_1': 'F',
					'media_value': 'N',
					'media_dock_value': 'N',
					'media_label_XY': 'N',
					'media_dock_XY': 'N',
					'play_option_L0_X': 233,
					'play_option_L0_Y': 259,
					'play_option_D0_X': 233,
					'play_option_D0_Y': 259,
					'label_Audio_Value': 'N',
					'label_play_option_value': 'N',
					'distractor_label': 'F',
					'FIB_value': 'N',
					'class_array_SEQ': 0,
					'edit_button_X': 5,
					'edit_button_Y': 0,
					'dock_hint_value': '%n%',
					'FIB_Dock': 'N',
					'doc_transparent_value': 'F',
					'visibility': true
			}],
		'SLEGV': '',
		'SLERQ': '',
		'SLERN': '',
		'SLEPS': {
			'totalRandomLabels': '', //Replace with SEQ count
			'disableFeedback': 'N',
			'disableInstantFeedback': 'N',
			'disableHints': 0,
			'studentGradeFormat': 'P'
		},
		'SLEGP': {
			'borderGlobal': 'T',
			'backGroundGlobal': 'T',
			'labelBorderGlobal': 'N',
			'labelBGGlobal': 'N',
			'dockBGGlobal': 'N'
		},
		'SLEDXY': '',
		'VST': 0,
		'SLEDS': '',
		'SLESD': '',
		'SLEDC': ''
};
